name: hubbub
version: 0.0.0
author: Tobe O <thosakwe@gmail.com>
description: Syntax extensions for the Dart language and parser, i.e. DSX.
homepage: https://github.com/regiostech/sdk/tree/master/pkg/hubbub
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  analyzer: ^0.36.0
  build: ^1.0.0
  build_config: ^0.4.0
  dart_style: ^1.0.0
  json_rpc_2: ^2.0.0
  package_resolver: ^1.0.0
  path: ^1.0.0
  pubspec_parse: ^0.1.4
  stream_channel: ^1.0.0
dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.0.0